### ISSUE TITLE
Ability to plot some standard things

### ISSUE THREAD

**Issue by jzabroski** [giacomelli/HarSharp#1]
The ability to parse Har in C# is great, but my actual use case is to plot body size and overall response time for a URL.  I am currently doing a very mickey mouse solution of using your parser library, extracting the fields I need to CSV, and then writing reports in Excel.  It would be great if there was some way to export all standard stats to CSV and then have some other utility to plot various things.

I may submit a patch or create an extension to your solution, but wanted to see your thoughts.

**Comment by giacomelli** [comment]
The idea is keep HarSharp simple, but export to CSV can be useful to others too. I think you can create a extension project on HarSharp repository, something like HarSharp.Extensions.Csv or create a new repository and reference it from HarSharp.
