### ISSUE TITLE
A gui for your work

### ISSUE THREAD

**Issue by AJ1000** [giacomelli/HarSharp#10]
I have written a win forms gui using HarSharp, based on the view google chrome gives. Happy to send you the code if it interests you. Thanks for the good work.

You can then publish it here if you wish. How do I get the code to you?

Ajay

**Comment by giacomelli** [comment]
Nice! You could add it as a sample for HarSharp.

Did you publish the code to a GitHub repository?

**Comment by AJ1000** [comment]
The code is available, how do I get it to you? I don’t know how to use github to upload to you.

**Comment by giacomelli** [comment]
You can send it to giacomelli@gmail.com

**Comment by AJ1000** [comment]
Code sent. Well done for the library.
