### ISSUE TITLE
.Net Standard / Core Support

### ISSUE THREAD

**Issue by dmasur** [giacomelli/HarSharp#4]
Hi there,

thanks for this Package. Is there any Support for .NetStandard in planing? Are there mayor problems?

**Comment by giacomelli** [comment]
Yes, I would like to support .NET Standard 2.0. 

The library is quite simple, so I guess will be easy add the support.

**Comment by hbagarich** [comment]
First of all thanks for the package!
I've played around for a bit, and it seems there is need to create new project that is targeting .NET Standard. You can copy all the files and it works (HelperSharp is minor problem, where you can just replace With extension method).
If you wish I can maybe open pull request with the changes needed?

**Comment by giacomelli** [comment]
@hbagarich yes, a pull request would be great!
