### ISSUE TITLE
.NET 4.0

### ISSUE THREAD

**Issue by jonweir** [giacomelli/HarSharp#5]
Hi there. Tried to install using NuGet PM and got:

"Could not install package 'HarSharp 1.0.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with 
that framework."

What framework is it compatible with please?

Thanks, Jon

**Comment by giacomelli** [comment]
* The version 1.0.0 is compatible with .NET Framework 4.5+.
* The version 2.0.0 is compatible with .NET Standard 2.0+.
